import LevelBuilder
from sprites import *
def render(name,bg):
    lb = LevelBuilder.LevelBuilder(name+".plist",background=bg)
    lb.addObject(Beam.BeamSprite(x=240, y=170,width=405,height=14,angle='0' ,restitution=0.2,static='false',friction=0.5,density=20 ))
    lb.addObject(Enemy.EnemySprite(x=240, y=219,width=32,height=32,angle='0',restitution=0.2,static='false',friction=0.5,density=20 ))
    lb.addObject(Friend.FriendSprite(x=477, y=4,width=32,height=32,angle='0',restitution=0.2,static='true',friction=0.5,density=20 ).setName('BottomRight'))
    lb.addObject(Friend.FriendSprite(x=477, y=320,width=32,height=32,angle='0',restitution=0.2,static='true',friction=0.5,density=20 ).setName('TopRight'))
    lb.addObject(Friend.FriendSprite(x=-1, y=320,width=32,height=32,angle='0',restitution=0.2,static='true',friction=0.5,density=20 ).setName('TopLeft'))
    lb.addObject(Friend.FriendSprite(x=-1, y=0,width=32,height=32,angle='0',restitution=0.2,static='true',friction=0.5,density=20 ).setName('BottomLeft'))
    lb.addObject(Joints.DistanceJoint(body1='TopLeft',body2='Beam',damping='0.2',freq='1' , b2_Xoffset = '-200' ))
    lb.addObject(Joints.DistanceJoint(body1='TopRight',body2='Beam',damping='0.2',freq='1' , b2_Xoffset = '200' ))
    lb.addObject(Joints.DistanceJoint(body1='BottomLeft',body2='Beam',damping='0.2',freq='1' , b2_Xoffset = '-200' ))
    lb.addObject(Joints.DistanceJoint(body1='BottomRight',body2='Beam',damping='0.2',freq='1' , b2_Xoffset = '200' ))
    lb.addObject(Hero.HeroSprite(x=191, y=32,width=32,height=32))
    lb.addObject(Star.StarSprite(x=240, y=255,width=32,height=32))
    lb.addObject(Enemy.EnemySprite(x=323, y=208,width=32,height=32,angle='0',restitution=0.2,static='false',friction=0.5,density=20 ))
    lb.addObject(Enemy.EnemySprite(x=122, y=197,width=32,height=32,angle='0',restitution=0.2,static='false',friction=0.5,density=20 ))
    lb.addObject(Enemy.EnemySprite(x=140, y=250,width=32,height=32,angle='0',restitution=0.2,static='false',friction=0.5,density=20 ))
    lb.addObject(Enemy.EnemySprite(x=369, y=269,width=32,height=32,angle='0',restitution=0.2,static='false',friction=0.5,density=20 ))
    lb.addObject(Friend.FriendSprite(x=88, y=245,width=32,height=32,angle='0',restitution=0.2,static='false',friction=0.5,density=20 ).setName('Friend_1'))
    lb.addObject(Enemy.EnemySprite(x=72, y=261,width=78,height=78,angle='0',restitution=0.2,static='false',friction=0.5,density=1 ).setName('Enemy_1'))
    lb.addObject(Joints.RevoluteJoint(body1='Enemy_1',body2='Friend_1',motor_speed='5',enable_motor='true',torque='1000',lower_angle='12',upper_angle='50',enable_limit='false',collide_connected='false'))
    lb.addObject(Friend.FriendSprite(x=433, y=204,width=32,height=32,angle='0',restitution=0.2,static='false',friction=0.5,density=20 ).setName('Friend_2'))
    lb.addObject(Enemy.EnemySprite(x=417, y=220,width=78,height=78,angle='0',restitution=0.2,static='false',friction=0.5,density=1 ).setName('Enemy_2'))
    lb.addObject(Joints.RevoluteJoint(body1='Enemy_2',body2='Friend_2',motor_speed='5',enable_motor='true',torque='1000',lower_angle='12',upper_angle='50',enable_limit='false',collide_connected='false'))
    lb.addObject(Contacts.Contact(body1='Hero',body2='Enemy_2',event_name='onLose'))
    lb.addObject(Contacts.Contact(body1='Hero',body2='Enemy_1',event_name='onLose'))
    lb.render()